#!/usr/bin/env bash

# DEPENDENCIES
# -------------------------------------------------------------------------------------------------
# - bash 4

# Imports
# -------------------------------------------------------------------------------------------------

IMPORT_COMMAND=${IMPORT_COMMAND:-"curl -s"}
LAZYSCRIPTS_REPOSITORY_URL=${REPOSITORY_URL:-"https://raw.githubusercontent.com/delucca/lazyscripts"}
LAZYSCRIPTS_REPOSITORY_BRANCH=${REPOSITORY_BRANCH:-"main"}

source <(eval "${IMPORT_COMMAND}" "${LAZYSCRIPTS_REPOSITORY_URL}/${LAZYSCRIPTS_REPOSITORY_BRANCH}/helpers/spinner.sh")
source <(eval "${IMPORT_COMMAND}" "${LAZYSCRIPTS_REPOSITORY_URL}/${LAZYSCRIPTS_REPOSITORY_BRANCH}/helpers/log.sh")
source <(eval "${IMPORT_COMMAND}" "${LAZYSCRIPTS_REPOSITORY_URL}/${LAZYSCRIPTS_REPOSITORY_BRANCH}/helpers/validators.sh")

# Entrypoint
# -------------------------------------------------------------------------------------------------

function main {
  validate_requirements

  if [ "${CODESPACES}" = "true" ]; then
    setup_codespaces
  else
    setup_local
  fi
}

# Validate requirements
# -------------------------------------------------------------------------------------------------

function validate_requirements {
  validate_bash_dependency
}

# Setup codespaces
# -------------------------------------------------------------------------------------------------

function setup_codespaces {
  log_title "SETUP CODESPACES"

  bootstrap_codespaces
}

function bootstrap_codespaces {
  log_title "BOOTSTRAP"

  source <(eval "${IMPORT_COMMAND}" "${REPOSITORY_URL}/${REPOSITORY_BRANCH}/bin/bootstrap-codespaces")
}

# Setup local
# -------------------------------------------------------------------------------------------------

function setup_code_env {
  log_title "SETUP LOCAL"

  bootstrap_local

function bootstrap_local {
  log_title "BOOTSTRAP"

  source <(eval "${IMPORT_COMMAND}" "${REPOSITORY_URL}/${REPOSITORY_BRANCH}/bin/bootstrap-code-env") --dotfiles
}

# Execute
# -------------------------------------------------------------------------------------------------

main
