vim.g.coc_global_extensions = {
  'coc-lists',
  'coc-snippets',
  'coc-docker',
  'coc-tsserver',
  'coc-prettier',
  'coc-eslint',
  'coc-tslint-plugin',
  'coc-highlight',
  'coc-sumneko-lua',
  'coc-sh',
  'coc-json',
  'coc-yaml',
  'coc-markdownlint',
  'coc-html',
  'coc-css',
  'coc-python',
}
