#!/usr/bin/env zsh

# Import min env
source "${HOME}/.zshenv.min"

# TMUX
export DISABLE_AUTO_TITLE='true'
export TMUXINATOR_CONFIG="${HOME}/.dotfiles/configs/tmuxinator"

# GPG
export GPG_TTY=$(tty)

# Minikube
export MINIKUBE_HOME='/home/minikube'

# PMY
export PMY_TRIGGER_KEY='^I'

# Spaceship
export SPACESHIP_KUBECTL_SHOW='true'

# FZF
export FZF_BASE='/home/git/junegunn/fzf'

# WSL
export WHOME='/mnt/c/Users/delucca'
