#!/usr/bin/env zsh

# Import min env
source "${HOME}/.zshenv.min"

# TMUX
export DISABLE_AUTO_TITLE='true'
export TMUXINATOR_CONFIG="${HOME}/.dotfiles/configs/tmuxinator"

# GPG
export GPG_TTY=$(tty)

# Minikube
export MINIKUBE_HOME='/home/minikube'

# PMY
export PMY_TRIGGER_KEY='^I'

# Spaceship
export SPACESHIP_KUBECTL_SHOW='true'

# FZF
export FZF_BASE='/home/git/junegunn/fzf'

# WSL
export WHOME='/mnt/c/Users/delucca'

# Pyenv
export PYENV_VERSION="3.10.4"
export PYENV_ROOT="$HOME/.pyenv"  

# Rigs
export IP_XCHRIG="10.243.80.12"

# WSL
export DISPLAY=$(grep -Po '(?<=nameserver ).*' /etc/resolv.conf):0

# Import local env
source "${HOME}/.zshenv.local"
