name: plato

windows:
- api:
    layout: main-vertical
    root: /home/delucca/src/trilon/plato/plato-api
    panes:
    - clear
- packages:
    layout: main-vertical
    root: /home/delucca/src/trilon/plato/plato-packages
    panes:
    - clear
