#!/usr/bin/env zsh

# Extend min config
# -------------------------------------------------------------------------------------------------

source "${HOME}/.zshrc.min"

# Configure tools
# -------------------------------------------------------------------------------------------------

# GPG keychain config
export GPG_TTY="$(tty)"
gpg-connect-agent updatestartuptty /bye > /dev/null

# SSH keychain config
export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/yubikey-agent/yubikey-agent.sock"

# AWS
autoload bashcompinit
bashcompinit

# Python pipx
autoload -U bashcompinit
bashcompinit

eval "$(register-python-argcomplete pipx)"

# Load plugins
# -------------------------------------------------------------------------------------------------

# # Improving ZSH usage
zinit light "changyuheng/fz"
zinit light "tcnksm/docker-alias"
zinit light "bonnefoa/kubectl-fzf"
zinit light "lukechilds/zsh-nvm"

# Post-plugin hook
# -------------------------------------------------------------------------------------------------

# Autoload tmux
if [ -z "$TMUX" ] && [[ $current_emulator == *"alacritty"* ]]; then
  tmuxinator start default
fi
