#!/usr/bin/env zsh

# Extend min config
# -------------------------------------------------------------------------------------------------

source "${HOME}/.zshrc.min"

# Configure tools
# -------------------------------------------------------------------------------------------------

# Keychain
zstyle :omz:plugins:keychain agents ssh,gpg
zstyle :omz:plugins:keychain identities id_ed25519

# Python pipx
autoload -U bashcompinit
bashcompinit

eval "$(register-python-argcomplete pipx)"

# Load plugins
# -------------------------------------------------------------------------------------------------

# Loading snippets
zinit snippet "OMZ::plugins/keychain/keychain.plugin.zsh"

# # Improving ZSH usage
zinit light "changyuheng/fz"
zinit light "tcnksm/docker-alias"
zinit light "bonnefoa/kubectl-fzf"
zinit light "lukechilds/zsh-nvm"

# Post-plugin hook
# -------------------------------------------------------------------------------------------------

# Autoload tmux
if [ -z "$TMUX" ] && [[ $current_emulator == *"alacritty"* ]]; then
  tmuxinator start default
fi
