#!/usr/bin/env zsh

# Configure tools
# -------------------------------------------------------------------------------------------------

current_emulator=$(pstree -sA $$)

# Keychain
zstyle :omz:plugins:keychain agents gpg,ssh
zstyle :omz:plugins:keychain identities id

# Compinit
autoload -U compinit && compinit

# Fresh
source ~/.fresh/build/shell.sh 

# FZF
source ~/.fzf.zsh

# Load plugins
# -------------------------------------------------------------------------------------------------

# Load zinit
source ${HOME}/.zinit/bin/zinit.zsh

# Load a few important annexes, without Turbo
zinit light-mode for \
  zinit-zsh/z-a-rust \
  zinit-zsh/z-a-as-monitor \
  zinit-zsh/z-a-patch-dl \
  zinit-zsh/z-a-bin-gem-node

# Oh-my-zsh configs that I want
zinit snippet "OMZ::lib/completion.zsh"
zinit snippet "OMZ::lib/history.zsh"
zinit snippet "OMZ::lib/key-bindings.zsh"
zinit snippet "OMZ::lib/theme-and-appearance.zsh"
zinit snippet "OMZ::lib/spectrum.zsh"
zinit snippet "OMZ::plugins/git/git.plugin.zsh"
zinit snippet "OMZ::plugins/git-extras/git-extras.plugin.zsh"
zinit snippet "OMZ::plugins/kubectl/kubectl.plugin.zsh"
zinit snippet "OMZ::plugins/dotenv/dotenv.plugin.zsh"
zinit snippet "OMZ::plugins/keychain/keychain.plugin.zsh"

# # Improving ZSH usage
zinit light "chrissicool/zsh-256color"
zinit light "rupa/z"
zinit light "changyuheng/fz"
zinit light "djui/alias-tips"
zinit light "supercrabtree/k"
zinit light "zsh-users/zsh-autosuggestions"
zinit light "zsh-users/zsh-syntax-highlighting"
zinit light "zsh-users/zsh-history-substring-search"
zinit light "Tarrasch/zsh-bd"
zinit light "changyuheng/zsh-interactive-cd"
zinit light "shannonmoeller/up"
zinit light "tcnksm/docker-alias"
zinit light "bonnefoa/kubectl-fzf"
zinit light "Aloxaf/fzf-tab"
zinit light "lukechilds/zsh-nvm"
# zinit light "b4b4r07/emoji-cli"
# /\ Waiting for this issue: https://github.com/b4b4r07/emoji-cli/issues/20

zinit cdreplay -q

# Autostart and post-plugin hook
# -------------------------------------------------------------------------------------------------

# Autoload tmux
if [ -z "$TMUX" ] && [[ $current_emulator == *"termite"* ]]; then
  tmuxinator start default
fi

# FZF-TAB
zstyle ':fzf-tab:complete:*' fzf-preview '
echo word: $word
echo description: $desc
(( $+ctxt[group] )) && echo group: $group
(( $+ctxt[isfile] )) && echo path: $realpath
'

zstyle ':fzf-tab:complete:cat:argument-rest' fzf-preview '[[ $(file --mime-type $realpath) == *"text/"* ]] && cat $realpath'

# Load Starship
eval "$(starship init zsh)"
