#!/usr/bin/env zsh

# Configure tools
# -------------------------------------------------------------------------------------------------

# Compinit
autoload -U compinit && compinit

# AWS
autoload bashcompinit
bashcompinit

# Python pipx
autoload -U bashcompinit
bashcompinit
eval "$(register-python-argcomplete pipx)"

# Java
eval "$(jenv init -)"

# Doppler
source /usr/local/share/zsh/site-functions/_doppler

# Bitwarden
source /usr/local/share/zsh/site-functions/_bw

# Load custom functions and aliases
source "${HOME}/.zfunctions"
source "${HOME}/.zaliases"

# Load plugins
# -------------------------------------------------------------------------------------------------

# Load zi
source ${HOME}/.zi/bin/zi.zsh
autoload -Uz _zi
(( ${+_comps} )) && _comps[zi]=_zi

# Load a few important annexes, without Turbo
zi light-mode for \
  z-shell/z-a-patch-dl \
  z-shell/z-a-bin-gem-node

# Load a few important annexes, without Turbo
zi light-mode for \
  z-shell/z-a-patch-dl \
  z-shell/z-a-bin-gem-node

# Oh-my-zsh configs that I want
zi snippet "OMZ::lib/completion.zsh"
zi snippet "OMZ::lib/history.zsh"
zi snippet "OMZ::lib/key-bindings.zsh"
zi snippet "OMZ::lib/theme-and-appearance.zsh"
zi snippet "OMZ::lib/spectrum.zsh"
zi snippet "OMZ::plugins/git/git.plugin.zsh"
zi snippet "OMZ::plugins/git-extras/git-extras.plugin.zsh"
zi snippet "OMZ::plugins/kubectl/kubectl.plugin.zsh"
zi snippet "OMZ::plugins/dotenv/dotenv.plugin.zsh"
zi snippet "OMZ::plugins/fzf/fzf.plugin.zsh"

# Improving ZSH usage
zi light "chrissicool/zsh-256color"
zi light "rupa/z"
zi light "djui/alias-tips"
zi light "supercrabtree/k"
zi light "zsh-users/zsh-autosuggestions"
zi light "zsh-users/zsh-syntax-highlighting"
zi light "zsh-users/zsh-history-substring-search"
zi light "Tarrasch/zsh-bd"
zi light "changyuheng/zsh-interactive-cd"
zi light "shannonmoeller/up"
zi light "Aloxaf/fzf-tab"
zi light "changyuheng/fz"
zi light "tcnksm/docker-alias"
zi light "bonnefoa/kubectl-fzf"

zi cdreplay -q

# Post-plugin hook
# -------------------------------------------------------------------------------------------------

# FZF-TAB
zstyle ':fzf-tab:complete:*' fzf-preview '
echo word: $word
echo description: $desc
(( $+ctxt[group] )) && echo group: $group
(( $+ctxt[isfile] )) && echo path: $realpath
'

zstyle ':fzf-tab:complete:cat:argument-rest' fzf-preview '[[ $(file --mime-type $realpath) == *"text/"* ]] && cat $realpath'

# Autoload tmux
if [ -z "$TMUX" ] && [ "$TERM_PROGRAM" != "vscode" ]; then
  tmuxinator start default
fi

# Load Starship
eval "$(starship init zsh)"
