#!/usr/bin/env bash

# FZF
# -------------------------------------------------------------------------------------------------

function fzf_history_widget_accept {
  fzf-history-widget
  zle accept-line
}

zle -N fzf_history_widget_accept
bindkey '^X^R' fzf_history_widget_accept

# Git
# -------------------------------------------------------------------------------------------------

function git_clone_repository {
  local org=$1
  local project=$2
  local repository="git@github.com:${org}/${project}.git"

  git clone $repository
}

function gcld {
  local org="delucca"

  git_clone_repository $org $@
}

# Helm
# -------------------------------------------------------------------------------------------------

function hl {
  helm list $@;
}

function hh {
  helm history $(helm list -q $@);
}

# Kubectl
# -------------------------------------------------------------------------------------------------

# Shell
# -------------------------------------------------------------------------------------------------

function fo {
  local files
  IFS=$'\n' file=($(fzf --query="$1" --exit-0))
  [[ -n "$file" ]] && xdg-open $file
}

function dotenv {
  local default_dotenv_path=".env"

  if [ -f "${default_dotenv_path}" ]; then
    export_dotenv_file "${default_dotenv_path}"
  fi

  for stage in $@; do
    local dotenv_path=".env.${stage}"

    if [ -f "${dotenv_path}" ]; then
      export_dotenv_file "${dotenv_path}"
    fi
  done
}

function export_dotenv_file {
  set -a
  eval $(cat "${1}" | sed -e '/^#/d;/^\s*$/d' -e 's/\(\w*\)[ \t]*=[ \t]*\(.*\)/\1=\2/' -e "s/=['\"]\(.*\)['\"]/=\1/g" -e "s/'/'\\\''/g" -e "s/=\(.*\)/='\1'/g")
  set +a
}

# Tmux
# -------------------------------------------------------------------------------------------------

function tns {
  tmux new -s $@ -d
  tmux switch -t $@
}

# Yubikey
# -------------------------------------------------------------------------------------------------

function yubikey_release {
  systemctl --user restart yubikey-agent
  killall -HUP yubikey-agent
  gpgconf --kill gpg-agent
}

# PNPM
# -------------------------------------------------------------------------------------------------

function use_pnpm6 {
  rm $HOME/.local/share/pnpm
  ln -s $HOME/.local/share/pnpm6 $HOME/.local/share/pnpm
}

function use_pnpm7 {
  rm $HOME/.local/share/pnpm
  ln -s $HOME/.local/share/pnpm7 $HOME/.local/share/pnpm
}

function sync_pnpm_with_npm {
  rm -rf node_modules package-lock.json pnpm-lock.yaml
  npm install
  rm -rf node_modules
  pnpm import
  pnpm install
}

# Networking
# -------------------------------------------------------------------------------------------------

function get_server_addr {
  export SERVER_ADDR=$(nmap -sP 172.16.0.0/24 >/dev/null && arp -an | grep ${SERVER_MAC_ADDR} | awk '{print $2}' | sed 's/[()]//g')
  echo ${SERVER_ADDR}
}

# WSL
# -------------------------------------------------------------------------------------------------

function attach_yubikey {
  sudo udevadm control --reload
  sudo service udev restart
  usbipd.exe attach --busid $(usbipd.exe list | rg "Smartcard" | cut -d' ' -f1) --wsl Debian
}
