#!/usr/bin/env bash

# Git
# -------------------------------------------------------------------------------------------------

alias gfum='git fetch upstream main'
alias gsum='gfum && git merge upstream/main'

# Zellij
# -------------------------------------------------------------------------------------------------

alias zj='zellij'

# Rest
# -------------------------------------------------------------------------------------------------

alias l='\k --human --group-directories-first'
alias la='l -A'
alias f='fzf'
alias c='xclip -sel clip'
alias v='xclip -sel clip -o'
alias cleartree='clear && tree -L 2'
alias vim='gvim -v'
alias tf='terraform'

# Node
# -------------------------------------------------------------------------------------------------
alias pn='pnpm'

# Neovim
# -------------------------------------------------------------------------------------------------
alias nv='nvim'
