#!/usr/bin/env bash

# Git
# -------------------------------------------------------------------------------------------------

alias gfum='git fetch upstream main'
alias gsum='gfum && git merge upstream/main'

# Kubectl
# -------------------------------------------------------------------------------------------------

alias kc='kubectl'
alias kx='kubectl ctx'
alias klf='kubectl logs --tail=200  -f'
alias kgs='kubectl get service -o wide'
alias kgd='kubectl get deployment -o wide'
alias kgp='kubectl get pod -o wide'
alias kgn='kubectl get node -o wide'
alias kdp='kubectl describe pod'
alias kds='kubectl describe service'
alias kdd='kubectl describe deployment'
alias kdf='kubectl delete -f'
alias kaf='kubectl apply -f'
alias kci='kubectl cluster-info'
alias kbad='kubectl get pod | grep "0\/"'
alias kre='kubectl get pod | sort -nk 4 | grep -v "Running   0"'
alias krey='kubectl get pod  | sort -nk 4 | grep -v "Running   0\|NAME" | cut -d" " -f1 | xargs -i kubectl describe pod {} | grep "Reason\|^Name:\|Finished"'
alias kall='kubectl get nodes --no-headers | awk '\''{print $1}'\'' | xargs -I {} sh -c '\''echo {} ; kubectl describe node {} | grep Allocated -A 5 | grep -ve Event -ve Allocated -ve percent -ve -- ; echo '\'''

# Minikube
# -------------------------------------------------------------------------------------------------

alias mk='minikube'
alias mks='minikube start'
alias mkq='minikube stop'
alias mkd='minikube delete'

# Tmux
# -------------------------------------------------------------------------------------------------

alias t='tmux'
alias td='tmux detach'
alias mux='tmuxinator'
alias tnw='tmux new-window -n'
alias tkw='tmux killw'
alias q='tmux kill-server'

# Rest
# -------------------------------------------------------------------------------------------------

alias hd='helm list --deployed | grep -v "NAME" | awk '\''{print $1}'\'' | sort | uniq -c  | awk '\''{print $1,$2}'\'' | grep -v  "^1 "'
alias l='\k --human --group-directories-first'
alias la='l -A'
alias f='fzf'
alias c='xclip -sel clip'
alias v='xclip -sel clip -o'
alias cleartree='clear && tree -L 2'
alias ykr='yubikey_release'
alias vim='gvim -v'
alias tf='terraform'
