#!/usr/bin/env zsh

# Zinit
export PLUGINS="$HOME/.zi/plugins"

# Editor
export EDITOR="nvim"

# Yubikey
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# Interface in general
export COMPLETION_WAITING_DOTS='true'

# FZF
export FZF_DEFAULT_OPTS="\
  --ansi \
  --cycle \
  --layout='reverse' \
  --height='20' \
  --preview='(highlight -O ansi -l {} 2> /dev/null || bat --style=numbers --color=always {} || cat {} || tree -L 2 -C {}) 2> /dev/null | head -200' \
  --preview-window='right:70%:noborder' \
  --bind='?:toggle-preview' \
  --bind='tab:down' \
"
export FZF_DEFAULT_COMMAND_OPTS="
  --hidden \
  --follow \
  --type='f' \
  --exclude='.git' \
"
export FZF_CTRL_R_OPTS="
  --sort \
  --exact \
  --preview-window='down:3:hidden:wrap' \
"
export FZF_CTRL_T_OPTS="
  --select-1 \
  --exit-0 \
"
export FZF_ALT_C_OPTS="
  --select-1 \
  --exit-0 \
"
export FZF_DEFAULT_COMMAND="fd ${FZF_DEFAULT_COMMAND_OPTS}"

export _ZO_FZF_OPTS="\
  --ansi \
  --cycle \
  --layout='reverse' \
  --height='20' \
  --preview='tree -L 2 -C {} | head -200' \
  --preview-window='right:70%:noborder' \
  --preview-window='right:70%:noborder' \
  --bind='?:toggle-preview' \
  --bind='tab:down' \
"

# Dotenv
export ZSH_DOTENV_PROMPT=false

# PMY
export PMY_TRIGGER_KEY='^I'

# Spaceship
export SPACESHIP_KUBECTL_SHOW='true'

# Pyenv
# export PYENV_VERSION="3.10.4"
export PYENV_ROOT="$HOME/.pyenv"  

# Rigs
export IP_XCHRIG="10.243.80.12"

# PNPM
export PNPM_HOME="/home/delucca/.local/share/pnpm"

# VOLTA
export VOLTA_HOME="/home/delucca/.volta"

# ZELLIJ
export ZELLIJ_CONFIG_DIR="/home/delucca/.zellij"

# PATH
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/bin:/bin"
export PATH="$PATH:/usr/local/sbin"
export PATH="$PATH:/usr/lib/jvm/default/bin"
export PATH="$PATH:/usr/bin/site_perl"
export PATH="$PATH:/usr/bin/vendor_perl"
export PATH="$PATH:/usr/bin/core_perl"
export PATH="$PATH:$HOME/.gem/ruby/2.6.0/bin"
export PATH="$PATH:/var/lib/snapd/snap/bin"
export PATH="$PATH:/snap/bin"
export PATH="$PATH:$HOME/.poetry/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:${KREW_ROOT:-$HOME/.krew}/bin"
export PATH="$PATH:$PYENV_ROOT/bin"
export PATH="$PATH:$PNPM_HOME"
export PATH="$PATH:/usr/local/cuda/bin"
export PATH="$PATH:$VOLTA_HOME/bin"
